const BillConstants = {
  CREATED_BILL: "CREATED_BILL",
  UPDATE_ALL_BILLS: "UPDATE_ALL_BILLS",
  FETCHED_ALL_BILLS: "FETCHED_ALL_BILLS",
  FETCHED_URGENT_BILLS: "FETCHED_URGENT_BILLS",
  FETCHED_COMPLETED_THIS_MONTH: "FETCHED_COMPLETED_THIS_MONTH"
};

module.exports = BillConstants;
