const BillConstants = {
  CREATED_BILL: "CREATED_BILL",
  UPDATE_ALL_BILLS: "UPDATE_ALL_BILLS",
  FETCHED_URGENT_BILLS: "FETCHED_URGENT_BILLS",
  FETCHED_THIS_MONTH: "FETCHED_THIS_MONTH",
  TOGGLE_COMPLETED: "TOGGLE_COMPLETED"
};

module.exports = BillConstants;
