const EventConstants = {
  RECEIVED_EVENTS: "RECEIVED_EVENTS",
  EVENT_CREATED: "EVENT_CREATED",
  EVENT_DELETED: "EVENT_DELETED",
  RECEIVE_UPCOMING_EVENTS: "RECEIVE_UPCOMING_EVENTS"
};

module.exports = EventConstants;
