const HouseConstants = {
  ADD_HOUSE: "ADD_HOUSE",
  HOUSEMATE_RECEIVED: "HOUSEMATE_RECEIVED",
  JOINED_HOUSE: "JOINED_HOUSE",
  UPDATE_CURRENT_HOUSE: "UPDATE_CURRENT_HOUSE"
};

module.exports = HouseConstants;
