const ListConstants = {
  RECEIVE_HOUSES_LISTS: "RECEIVE_HOUSES_LISTS",
  CREATED_LIST: "CREATED_LIST",
  UPDATED_LIST: "UPDATED_LIST",
  UPDATED_LIST_ITEM: "UPDATED_LIST_ITEM"
};

module.exports = ListConstants;
