# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dd24137248eda041791e581ebd164f27e24ec52fac62e946651be7d4604a7f1a41a4a364055cbb3ca28794974514b8a17eb07df33346ce2117cfa5f5add7269

test:
  secret_key_base: eec36fa83a216ebbd7a83ebd03945c22007cebb6af189fcef0cff33a0c908c0b0da98701408ebf794d3118b809bdea3aa266761816d797e92e55345366facc4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
